import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-100 p-5 font-sans text-gray-800">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between space-y-4 sm:space-y-0">
            <h1 className="text-2xl sm:text-2xl md:text-2xl lg:text-3xl xl:text-4xl font-extrabold">
              Feedback Form
            </h1>
            <div className="flex flex-col sm:flex-row sm:items-center sm:space-x-6 space-y-2 sm:space-y-0">
              <Link
                href="/feedbackpage"
                className="text-blue-600 hover:underline text-lg sm:text-xl lg:text-2xl font-bold"
              >
                Feedback Responses
              </Link>
              <Link
                href="/"
                className="text-blue-600 hover:underline text-lg sm:text-xl lg:text-2xl font-bold"
              >
                Share your Feedback
              </Link>
            </div>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
